sudo: false
language: ruby
bundler_args: --jobs=2
script:  bundle exec rspec
rvm:
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails_5_0_0.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
before_install: gem install bundler -v 1.16.2
